### ISSUE TITLE
windows issue: config cannot be found

### ISSUE THREAD

**Issue by jeroenver** [milanaleksic/clici#28]
On startup I'm getting:
2016/09/22 13:48:46 Failure while parsing configuration file clici-0.2.1-windows-amd64.exe/clici.toml: open clici.toml: The system cannot find the file specified.. If you wish to set up default configuration file, please use -make-default-config argument

I do have a clicli.toml file next to the exe.

Default config seems to fail as well:
clici-0.2.1-windows-amd64.exe -make-default-config
2016/09/22 13:51:48 Could not create default TOML configuration file: Error reading asset cmd/main/data/default-configuration.toml at /opt/go/src/github.com/milanaleksic/clici/cmd/main/data/default-configuration.toml: open /opt/go/src/github.com/milanaleksic/clici/cmd/main/data/default-configuration.toml: The system cannot find the path specified.

**Comment by jeroenver** [comment]
ok, the startup is now working, my old jenkins_ping.toml seemed to be incompatible.
The default config creation is still not working though.

**Comment by milanaleksic** [comment]
confirmed, windows is broken, will look into it

**Comment by milanaleksic** [comment]
@jeroenver could you retry with 0.2.2? The issues was in the build script, I've mistakenly created a binary partially in "debug" mode with file instead of in-memory references

0.2.1 had this issue:
```bash
milan@phobos /opt/go/src/github.com/milanaleksic/clici → strace ~/Downloads/clici-0.2.1-linux-amd64 -make-default-config 2>&1 | grep open
open("/lib64/ld-linux-x86-64.so.2", O_RDONLY) = 3
open("/etc/ld.so.cache", O_RDONLY|O_CLOEXEC) = 3
open("/lib/x86_64-linux-gnu/libpthread.so.0", O_RDONLY|O_CLOEXEC) = 3
open("/lib/x86_64-linux-gnu/libc.so.6", O_RDONLY|O_CLOEXEC) = 3
openat(AT_FDCWD, "/proc/sys/net/core/somaxconn", O_RDONLY|O_CLOEXEC) = 3
openat(AT_FDCWD, "/opt/go/src/github.com/milanaleksic/clici/cmd/main/data/default-configuration.toml", O_RDONLY|O_CLOEXEC) = 3
openat(AT_FDCWD, "/home/milan/Downloads/clici.toml", O_WRONLY|O_CREAT|O_TRUNC|O_CLOEXEC, 0666) = 3
``` 

but the 0.2.2 hopefully doesn't have it any more:

```bash
milan@phobos /opt/go/src/github.com/milanaleksic/clici → strace ~/Downloads/clici-0.2.2-linux-amd64 -make-default-config 2>&1 | grep open
open("/lib64/ld-linux-x86-64.so.2", O_RDONLY) = 3
open("/etc/ld.so.cache", O_RDONLY|O_CLOEXEC) = 3
open("/lib/x86_64-linux-gnu/libpthread.so.0", O_RDONLY|O_CLOEXEC) = 3
open("/lib/x86_64-linux-gnu/libc.so.6", O_RDONLY|O_CLOEXEC) = 3
openat(AT_FDCWD, "/proc/sys/net/core/somaxconn", O_RDONLY|O_CLOEXEC) = 3
openat(AT_FDCWD, "/home/milan/Downloads/clici.toml", O_WRONLY|O_CREAT|O_TRUNC|O_CLOEXEC, 0666) = 3
```

**Comment by jeroenver** [comment]
ok, this is indeed solved
